name: deploy_backend_net8

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'backend/api-net8/**'

env:
  AZURE_FUNCTIONAPP_NAME: GetVisitorCounter
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'
  DOTNET_VERSION: '8.0'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login via Azure CLI'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/api-net8'
          dotnet build --configuration Release --output ./output
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/api-net8/output'

      - name: Azure Logout
        run: az logout
        if: always()
