name: deploy_frontend
# Deploys when push is made from frontend folder

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

env:
  STORAGE_ACCOUNT: azureresumestoragejames
  CDN_PROFILE: azureresumejamesdean
  CDN_ENDPOINT: azureresumejamesdean
  RESOURCE_GROUP: azureresume-rg

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ env.STORAGE_ACCOUNT }} \
              -d '$web' \
              -s frontend/

      - name: Purge CDN endpoint
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az cdn endpoint purge \
              --content-paths "/*" \
              --profile-name "${{ env.CDN_PROFILE }}" \
              --name "${{ env.CDN_ENDPOINT }}" \
              --resource-group "${{ env.RESOURCE_GROUP }}"

      - name: Azure Logout
        run: az logout
        if: always()
